# Generated by Django 4.0.4 on 2022-05-14 07:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('carid', models.IntegerField(db_column='CarID', primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=20, null=True)),
                ('model_year', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20, null=True)),
                ('engine_size', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.IntegerField(db_column='PersonID', primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('carid', models.IntegerField(blank=True, db_column='CarID', null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
